# Generated by Django 5.0.2 on 2024-04-01 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiusers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminf',
            name='email',
        ),
        migrations.RemoveField(
            model_name='admins',
            name='email',
        ),
        migrations.RemoveField(
            model_name='admint',
            name='email',
        ),
        migrations.RemoveField(
            model_name='doctorant',
            name='email',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=100),
        ),
    ]
