# Generated by Django 5.0.4 on 2024-05-25 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiusers', '0002_remove_adminf_email_remove_admins_email_and_more'),
        ('authtoken', '0004_alter_tokenproxy_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomToken',
            fields=[
                ('token_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='authtoken.token')),
                ('expiration', models.DateTimeField()),
            ],
            bases=('authtoken.token',),
        ),
    ]
