# Generated by Django 5.0.4 on 2024-05-25 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiusers', '0003_customtoken'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomToken',
        ),
    ]
