# Generated by Django 5.0.4 on 2024-06-02 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ResponsiveHeaderIMGs', '0002_gererheader'),
    ]

    operations = [
        migrations.AddField(
            model_name='gererheader',
            name='action',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
