# Generated by Django 5.0.2 on 2024-03-07 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Labo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20)),
                ('Codelabo', models.CharField(max_length=100, unique=True)),
                ('Directeur', models.CharField(max_length=200)),
                ('Discipline', models.CharField(max_length=200)),
                ('Etablissement', models.CharField(max_length=200)),
                ('fiche', models.FileField(upload_to='store/files/')),
            ],
        ),
    ]
