# Generated by Django 5.0.2 on 2024-04-13 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chercheur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.CharField(default='none', max_length=255)),
                ('Prenom', models.CharField(default='none', max_length=255)),
                ('email', models.EmailField(default='none', max_length=254)),
                ('cin', models.CharField(max_length=20, unique=True)),
                ('tel', models.CharField(default='none', max_length=15)),
                ('SujetThese', models.TextField(default='none')),
                ('Address', models.TextField(default='none')),
                ('dateNaissance', models.DateField(default='2000-01-01')),
                ('lieuNaissance', models.CharField(max_length=255)),
                ('StructureRecherche', models.CharField(max_length=255)),
                ('specialite', models.CharField(max_length=255)),
                ('FirstDirTheseName', models.CharField(max_length=255)),
                ('FirstDirTheseGrade', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('FirstDirTheseLieuTravail', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('FirstDirTheseEmail', models.EmailField(blank=True, default=None, max_length=254, null=True)),
                ('FirstDirThesePhone', models.CharField(blank=True, default=None, max_length=15, null=True)),
                ('TypeThese', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('SecondDirTheseName', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('SecondDirTheseGrade', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('SecondDirTheseLieuTravail', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('SecondDirTheseEmail', models.EmailField(blank=True, max_length=254, null=True)),
                ('SecondDirTheseStructureRecherche', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('SecondDirThesePhone', models.CharField(blank=True, default=None, max_length=15, null=True)),
                ('convention', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('CoEncadrantName', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('CoEncadrantGrade', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('CoEncadrantLieuTravail', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('CoEncadrantEmail', models.EmailField(blank=True, max_length=254, null=True)),
                ('CoEncadrantPhone', models.CharField(blank=True, default=None, max_length=15, null=True)),
                ('State', models.CharField(default='En attente', max_length=200)),
                ('Niveau', models.CharField(default='1ere année', max_length=233)),
                ('FirstYearInscription', models.CharField(default='none', max_length=323)),
                ('is_inscrit', models.BooleanField(default=0)),
            ],
        ),
    ]
