# Generated by Django 5.0.4 on 2024-04-23 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chercheur', '0002_chercheur_etablissement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chercheur',
            name='FirstYearInscription',
            field=models.CharField(max_length=323, null=True),
        ),
    ]
