# Generated by Django 5.0.4 on 2024-04-23 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chercheur', '0004_alter_chercheur_datenaissance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chercheur',
            name='dateNaissance',
            field=models.DateField(auto_now_add=True),
        ),
    ]
