# Generated by Django 5.0.4 on 2024-04-23 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chercheur', '0006_alter_chercheur_datenaissance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chercheur',
            name='dateNaissance',
            field=models.CharField(default='2000-01-01', max_length=200),
        ),
    ]
