# Generated by Django 5.0.4 on 2024-05-16 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chercheur', '0009_assurerisncription'),
    ]

    operations = [
        migrations.AddField(
            model_name='assurerisncription',
            name='action',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
