# Generated by Django 5.0.4 on 2024-05-17 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chercheur', '0010_assurerisncription_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='chercheur',
            name='image',
            field=models.ImageField(default='none', upload_to='image/logo/'),
        ),
    ]
