# Generated by Django 5.0.4 on 2024-05-25 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chercheur', '0011_chercheur_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chercheur',
            name='image',
            field=models.ImageField(default='profile.jpg', upload_to='image/logo/'),
        ),
    ]
