# Generated by Django 5.0.4 on 2024-05-25 14:33

import chercheur.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chercheur', '0014_alter_chercheur_firstyearinscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chercheur',
            name='FirstYearInscription',
            field=models.CharField(default=chercheur.models.current_year, max_length=323, null=True),
        ),
    ]
