# Generated by Django 5.0.2 on 2024-04-15 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demandes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='demandes',
            old_name='niveau',
            new_name='Langue',
        ),
        migrations.RemoveField(
            model_name='demandes',
            name='Address',
        ),
        migrations.RemoveField(
            model_name='demandes',
            name='StructureRecherche',
        ),
        migrations.RemoveField(
            model_name='demandes',
            name='SujetThese',
        ),
        migrations.RemoveField(
            model_name='demandes',
            name='TypeThese',
        ),
        migrations.RemoveField(
            model_name='demandes',
            name='dateNaissance',
        ),
        migrations.RemoveField(
            model_name='demandes',
            name='lieuNaissance',
        ),
        migrations.RemoveField(
            model_name='demandes',
            name='nomChercheur',
        ),
        migrations.RemoveField(
            model_name='demandes',
            name='prenomChercheur',
        ),
        migrations.RemoveField(
            model_name='demandes',
            name='specialite',
        ),
        migrations.RemoveField(
            model_name='demandes',
            name='tel',
        ),
        migrations.AddField(
            model_name='demandes',
            name='nbCopie',
            field=models.CharField(default='1', max_length=200),
        ),
    ]
