# Generated by Django 5.0.2 on 2024-04-15 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demandes', '0002_rename_niveau_demandes_langue_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandes',
            name='DateDepot',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='demandes',
            name='State',
            field=models.CharField(default='En attente', max_length=100),
        ),
    ]
