# Generated by Django 5.0.4 on 2024-05-16 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demandes', '0004_remove_demandes_cin_demandes_chercheur'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandes',
            name='cin',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
