# Generated by Django 5.0.4 on 2024-05-27 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demandes', '0005_demandes_cin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demandes',
            name='cin',
        ),
    ]
