# Generated by Django 5.0.4 on 2024-05-09 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chercheur', '0008_alter_chercheur_convention'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='store/files/')),
            ],
        ),
        migrations.CreateModel(
            name='These',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('specialite', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='store/files/')),
                ('date_soutenu', models.DateField()),
                ('state', models.CharField(default='non-validé', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='store/files/')),
                ('date_depot', models.DateField()),
                ('state', models.CharField(default='non-validé', max_length=100)),
                ('chercheur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='chercheur.chercheur')),
            ],
        ),
    ]
