# Generated by Django 5.0.4 on 2024-05-09 17:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bibliotheque', '0001_initial'),
        ('chercheur', '0008_alter_chercheur_convention'),
        ('directeurs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='directeur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='directeurs.directeur'),
        ),
        migrations.AddField(
            model_name='document',
            name='idadmin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='these',
            name='chercheur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='chercheur.chercheur'),
        ),
        migrations.AddField(
            model_name='these',
            name='directeur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='directeurs.directeur'),
        ),
    ]
