export const DOCTORANT_USER_LOADED="DOCTORANT_USER_LOADED";
export const DOCTORANT_USER_FAILED="DOCTORANT_USER_FAILED";

export const ADMINF_USER_LOADED="ADMINF_USER_LOADED";
export const ADMINF_USER_FAILED="ADMINF_USER_FAILED";

export const ADMINS_USER_LOADED="ADMINS_USER_LOADED";
export const ADMINS_USER_FAILED="ADMINS_USER_FAILED";

export const ADMINT_USER_LOADED="ADMINT_USER_LOADED";
export const ADMINT_USER_FAILED="ADMINT_USER_FAILED";

export const LOGIN_SUCCESS="LOGIN_SUCCESS";
export const LOGIN_FAILED="LOGIN_FAILED";
export const LOGOUT_SUCCESS="LOGOUT_SUCCESS";

export const REGISTER_A1USER_SUCCESS="REGISTER_A1USER_SUCCESS";
export const REGISTER_A1USER_FAILED="REGISTER_A1USER_FAILED";

export const REGISTER_A2USER_SUCCESS="REGISTER_A2USER_SUCCESS";
export const REGISTER_A2USER_FAILED="REGISTER_A2USER_FAILED";

export const REGISTER_A3USER_SUCCESS="REGISTER_A3USER_SUCCESS";
export const REGISTER_A3USER_FAILED="REGISTER_A3USER_FAILED";

export const REGISTER_DUSER_SUCCESS="REGISTER_CUSER_SUCCESS";
export const REGISTER_DUSER_FAILED="REGISTER_CUSER_FAILED";