# Generated by Django 5.0.2 on 2024-04-22 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Etablissement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='image/logo/')),
                ('nom', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('tel', models.CharField(max_length=200)),
                ('fax', models.CharField(max_length=200)),
            ],
        ),
    ]
