# Generated by Django 5.0.2 on 2024-04-02 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormationPedagogique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('prenom', models.CharField(max_length=200)),
                ('cin', models.CharField(max_length=200)),
                ('niveau', models.CharField(max_length=200)),
                ('tel', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('specialite', models.CharField(max_length=200)),
                ('nom_formation', models.CharField(max_length=200)),
                ('nom_formateur', models.CharField(max_length=200)),
                ('lieu_formation', models.CharField(max_length=200)),
                ('state', models.CharField(default='non-validé', max_length=200)),
                ('date_creation', models.DateField(auto_now_add=True)),
                ('nombre_heure', models.IntegerField()),
                ('file', models.FileField(upload_to='store/files/')),
                ('annee_universitaire', models.CharField(max_length=9)),
                ('semestre', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='FormationSimple',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('prenom', models.CharField(max_length=200)),
                ('cin', models.CharField(max_length=200)),
                ('niveau', models.CharField(max_length=200)),
                ('tel', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('specialite', models.CharField(max_length=200)),
                ('nom_formation', models.CharField(max_length=200)),
                ('nom_formateur', models.CharField(max_length=200)),
                ('lieu_formation', models.CharField(max_length=200)),
                ('state', models.CharField(default='non-validé', max_length=200)),
                ('date_creation', models.DateField(auto_now_add=True)),
                ('nombre_heure', models.IntegerField()),
                ('file', models.FileField(upload_to='store/files/')),
                ('type', models.CharField(max_length=200)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
            ],
        ),
    ]
