# Generated by Django 5.0.4 on 2024-05-28 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0003_remove_formationpedagogique_cin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formationpedagogique',
            name='email',
        ),
        migrations.RemoveField(
            model_name='formationpedagogique',
            name='niveau',
        ),
        migrations.RemoveField(
            model_name='formationpedagogique',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='formationpedagogique',
            name='prenom',
        ),
        migrations.RemoveField(
            model_name='formationpedagogique',
            name='specialite',
        ),
        migrations.RemoveField(
            model_name='formationpedagogique',
            name='tel',
        ),
        migrations.RemoveField(
            model_name='formationsimple',
            name='email',
        ),
        migrations.RemoveField(
            model_name='formationsimple',
            name='niveau',
        ),
        migrations.RemoveField(
            model_name='formationsimple',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='formationsimple',
            name='prenom',
        ),
        migrations.RemoveField(
            model_name='formationsimple',
            name='specialite',
        ),
        migrations.RemoveField(
            model_name='formationsimple',
            name='tel',
        ),
    ]
